server:
  port: 8013

spring:
  application:
    name: order-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        weight: 30
        enabled: false #不让本服务注册到nacos上